---
settings:
  name: NetApp Workload Factory
  search: workload-setup-admin,workload-fsx-ontap,workload-databases,workload-vmware,workload-genai,workload-eda,workload-relnotes
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
    lipi_enabled: true
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Toute la documentation de Workload Factory
    url: "/index.html"
