= Suivez et surveillez les opérations
:allow-uri-read: 


[role="lead"]
Surveillez et suivez l’exécution des opérations de charge de travail et surveillez la progression des tâches avec Tracker dans NetApp Workload Factory.

.Description de la tâche
NetApp Workload Factory fournit Tracker, une fonctionnalité de surveillance, qui vous permet de surveiller et de suivre la progression et l'état des opérations de charge de travail, d'examiner les détails des tâches et sous-tâches d'opération et de diagnostiquer les problèmes ou les pannes.

Plusieurs actions sont disponibles dans Tracker. Vous pouvez filtrer les travaux par période (24 heures, 7 jours, 14 jours ou 30 jours), charge de travail, état et utilisateur, rechercher des travaux à l'aide de la fonction de recherche et télécharger la table des travaux sous forme de fichier CSV. Vous pouvez actualiser le Tracker à tout moment et réessayer rapidement une opération ayant échoué ou modifier les paramètres d'une opération ayant échoué et réessayer l'opération.

Tracker prend en charge deux niveaux de surveillance en fonction de l'opération. Chaque tâche, telle que le déploiement du système de fichiers, affiche la description de la tâche, l'état, l'heure de début, la durée de la tâche, l'utilisateur, la région, la ressource proxy, l'ID de la tâche et toutes les sous-tâches associées. Vous pouvez afficher les réponses de l'API pour comprendre ce qui s'est passé pendant l'opération.

Niveaux de tâche de suivi avec des exemples::
+
--
* Niveau 1 (tâche) : assure le suivi du déploiement du système de fichiers.
* Niveau 2 (sous-tâche) : effectue le suivi des sous-tâches liées au déploiement du système de fichiers.


--
État de l'opération:: L'état d'opération dans le Tracker est le suivant : _in Progress_, _Success_ et _failed_.
+
--
Fréquence de fonctionnement:: La fréquence des opérations est basée sur le type de travail et le planning de travail.


--
Conservation des événements:: Les événements sont conservés dans l'interface utilisateur pendant 30 jours.




== Suivez et surveillez les opérations

Suivez et surveillez les opérations dans la console Workload Factory avec Tracker.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans le menu de charge de travail, sélectionnez *Administration* puis *Tracker*.
. Dans Tracker, utilisez les filtres ou effectuez une recherche pour affiner les résultats des emplois.  Vous pouvez également télécharger un rapport sur les emplois.




== Afficher une demande d'API

Affichez la demande API dans la zone de code pour une tâche dans Tracker.

.Étapes
. Dans Tracker, sélectionnez une tâche.
. Sélectionnez le menu Actions, puis sélectionnez *Afficher la demande API*.




== Réessayez une opération ayant échoué

Réessayez une opération ayant échoué dans le Tracker. Vous pouvez également copier le message d'erreur d'une opération ayant échoué.


NOTE: Vous pouvez réessayer une opération ayant échoué jusqu'à 10 fois.

.Étapes
. Dans Tracker, sélectionnez une opération ayant échoué.
. Sélectionnez le menu Actions, puis sélectionnez *Réessayer*.


.Résultat
L'opération est lancée à nouveau.



== Modifiez et réessayez une opération ayant échoué

Modifiez les paramètres de l'opération ayant échoué et relancez l'opération en dehors du Tracker.

.Étapes
. Dans Tracker, sélectionnez une opération ayant échoué.
. Sélectionnez le menu Actions, puis sélectionnez *Modifier et réessayer*.
+
Vous êtes redirigé vers la page d'opération où vous pouvez modifier les paramètres et réessayer l'opération.



.Résultat
L'opération est lancée à nouveau. Accédez à Tracker pour afficher l'état de l'opération.
